export function exportMarkdown(content: string, label: string): void {
  const blob = new Blob([content], { type: "text/markdown" });
  downloadBlob(blob, `flowprd-${label}.md`);
}

export function exportPlainText(content: string, label: string): void {
  // Strip markdown formatting
  const plain = content
    .replace(/^#{1,6}\s+/gm, "") // headings
    .replace(/\*\*(.*?)\*\*/g, "$1") // bold
    .replace(/\*(.*?)\*/g, "$1") // italic
    .replace(/`([^`]+)`/g, "$1") // inline code
    .replace(/```[\s\S]*?```/g, "") // code blocks
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // links
    .replace(/^[-*]\s+/gm, "• ") // list items
    .replace(/^\d+\.\s+/gm, (match) => match) // ordered lists
    .replace(/^\|.*\|$/gm, "") // table rows
    .replace(/^---+$/gm, "") // hr
    .replace(/\n{3,}/g, "\n\n") // multiple newlines
    .trim();

  const blob = new Blob([plain], { type: "text/plain" });
  downloadBlob(blob, `flowprd-${label}.txt`);
}

export function exportHTML(content: string, label: string): void {
  // Convert markdown to basic HTML
  const html = `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FlowPRD - ${label.toUpperCase()}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; line-height: 1.7; }
    h1 { font-size: 1.5rem; border-bottom: 2px solid #f97316; padding-bottom: 8px; }
    h2 { font-size: 1.25rem; margin-top: 2rem; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; }
    h3 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.08em; color: #f97316; margin-top: 1.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th { background: #f5f5f5; padding: 8px 12px; text-align: left; border: 1px solid #ddd; font-size: 0.8rem; text-transform: uppercase; }
    td { padding: 8px 12px; border: 1px solid #ddd; }
    code { background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }
    pre { background: #f5f5f5; padding: 16px; border-radius: 6px; overflow-x: auto; }
    blockquote { border-left: 3px solid #f97316; padding-left: 16px; color: #666; }
    ul li { list-style-type: "›  "; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e5e5; font-size: 0.75rem; color: #999; }
  </style>
</head>
<body>
${markdownToHtml(content)}
<div class="footer">Generated by FlowPRD</div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  downloadBlob(blob, `flowprd-${label}.html`);
}

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>')
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/^---+$/gm, "<hr>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hulo]|<\/|<hr|<str|<em|<cod|<a|<blo)(.+)$/gm, "<p>$1</p>");
}

export function exportDOCX(content: string, label: string): void {
  // DOCX via HTML (Word can open this)
  const html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset="UTF-8">
<style>
body { font-family: Calibri, sans-serif; font-size: 11pt; line-height: 1.5; }
h1 { font-size: 18pt; color: #f97316; border-bottom: 2pt solid #f97316; }
h2 { font-size: 14pt; border-bottom: 1pt solid #ddd; padding-bottom: 4pt; }
h3 { font-size: 10pt; text-transform: uppercase; letter-spacing: 1pt; color: #f97316; }
table { border-collapse: collapse; width: 100%; }
td, th { border: 1pt solid #ddd; padding: 4pt 8pt; font-size: 10pt; }
th { background: #f5f5f5; }
</style></head><body>${markdownToHtml(content)}</body></html>`;

  const blob = new Blob([html], { type: "application/vnd.ms-word" });
  downloadBlob(blob, `flowprd-${label}.doc`);
}

export function exportNotion(content: string, label: string): void {
  // Notion-compatible markdown (clean, no HTML)
  const notionMd = content
    .replace(/^#{1,3}\s+/gm, (match) => match) // keep headings
    .replace(/\*\*(.+?)\*\*/g, "**$1**") // keep bold
    .replace(/\*(.+?)\*/g, "*$1*") // keep italic
    .replace(/^- (.+)$/gm, "- $1") // keep bullets
    .replace(/^\|(.+)\|$/gm, (match) => {
      // Clean table for Notion
      const cells = match.split("|").filter(Boolean).map((c) => c.trim());
      if (cells.every((c) => /^[-:]+$/.test(c))) return "";
      return "| " + cells.join(" | ") + " |";
    })
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const blob = new Blob([notionMd], { type: "text/markdown" });
  downloadBlob(blob, `flowprd-${label}-notion.md`);
}

export function exportPresentation(content: string, label: string): void {
  // Split content into slides by ## headings
  const sections = content.split(/^## /gm).filter(Boolean);
  const slides = sections.map((section, i) => {
    const lines = section.trim().split("\n");
    const title = lines[0]?.trim() || `Slide ${i + 1}`;
    const body = lines.slice(1).join("\n").trim();
    return { title, body };
  });

  const slidesHtml = slides
    .map(
      (slide, i) => `
    <div class="slide" id="slide-${i}" ${i > 0 ? 'style="display:none"' : ""}>
      <div class="slide-content">
        <h1>${slide.title}</h1>
        <div class="slide-body">${markdownToHtml(slide.body)}</div>
      </div>
      <div class="slide-number">${i + 1} / ${slides.length}</div>
    </div>`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<title>FlowPRD — ${label}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #0c0d11; color: #e4e4e7; }
.slide { width: 100vw; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 60px; }
.slide-content { max-width: 800px; width: 100%; }
h1 { font-size: 2.5rem; font-weight: 700; margin-bottom: 2rem; color: #f97316; }
.slide-body { font-size: 1.2rem; line-height: 1.8; color: #a1a1aa; }
.slide-body h2 { font-size: 1.5rem; color: #e4e4e7; margin: 1.5rem 0 0.5rem; }
.slide-body h3 { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.1em; color: #f97316; margin: 1rem 0 0.5rem; }
.slide-body ul { padding-left: 1.5rem; margin: 0.5rem 0; }
.slide-body li { margin: 0.3rem 0; }
.slide-body table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }
.slide-body td, .slide-body th { padding: 0.5rem; border: 1px solid #22232e; text-align: left; }
.slide-body th { background: #181920; color: #e4e4e7; }
.slide-body strong { color: #e4e4e7; }
.slide-number { position: fixed; bottom: 20px; right: 30px; font-size: 0.8rem; color: #52525b; font-family: monospace; }
.nav { position: fixed; bottom: 20px; left: 30px; display: flex; gap: 8px; }
.nav button { padding: 8px 16px; background: #181920; border: 1px solid #22232e; color: #a1a1aa; border-radius: 6px; cursor: pointer; font-size: 0.8rem; }
.nav button:hover { border-color: #f97316; color: #f97316; }
</style>
</head>
<body>
${slidesHtml}
<div class="nav">
  <button onclick="prev()">← Prev</button>
  <button onclick="next()">Next →</button>
</div>
<script>
let current = 0;
const total = ${slides.length};
function show(n) {
  document.querySelectorAll('.slide').forEach(s => s.style.display = 'none');
  document.getElementById('slide-' + n).style.display = 'flex';
  current = n;
}
function next() { if (current < total - 1) show(current + 1); }
function prev() { if (current > 0) show(current - 1); }
document.addEventListener('keydown', e => {
  if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); next(); }
  if (e.key === 'ArrowLeft') { e.preventDefault(); prev(); }
});
</script>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  downloadBlob(blob, `flowprd-${label}-presentation.html`);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
