"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { MarkdownRenderer } from "@/components/MarkdownRenderer";
import Link from "next/link";

interface SharedDoc {
  title: string;
  prd_content: string;
  workflow_content: string;
  view_count: number;
}

export default function SharePage() {
  const params = useParams();
  const token = params.token as string;
  const [doc, setDoc] = useState<SharedDoc | null>(null);
  const [tab, setTab] = useState<"prd" | "workflow">("prd");
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (!token) return;
    const supabase = createClient();
    supabase
      .from("share_links")
      .select("title, prd_content, workflow_content, view_count")
      .eq("token", token)
      .single()
      .then(({ data, error }) => {
        if (error || !data) {
          setNotFound(true);
        } else {
          setDoc(data);
          // Increment view count
          supabase
            .from("share_links")
            .update({ view_count: (data.view_count || 0) + 1 })
            .eq("token", token)
            .then(() => {});
        }
        setLoading(false);
      });
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen bg-bg flex items-center justify-center">
        <span className="w-2 h-2 rounded-full bg-orange animate-pulse" />
      </div>
    );
  }

  if (notFound || !doc) {
    return (
      <div className="min-h-screen bg-bg flex items-center justify-center">
        <div className="text-center">
          <p className="text-ink-mid mb-4">Link tidak ditemukan</p>
          <Link href="/" className="text-[12px] text-aqua hover:underline">
            Kembali ke beranda
          </Link>
        </div>
      </div>
    );
  }

  const content = tab === "prd" ? doc.prd_content : doc.workflow_content;

  return (
    <div className="min-h-screen bg-bg flex flex-col">
      {/* Header */}
      <header className="flex items-center justify-between px-6 h-12 border-b border-border bg-panel">
        <Link href="/" className="flex items-center gap-2">
          <div className="flex gap-[3px]">
            <div className="w-[3px] h-3 rounded-[1px] bg-orange" />
            <div className="w-[3px] h-3 rounded-[1px] bg-orange/40" />
            <div className="w-[3px] h-3 rounded-[1px] bg-orange/15" />
          </div>
          <span className="text-[13px] font-semibold tracking-tight ml-1">FlowPRD</span>
        </Link>
        <span className="text-[10px] font-mono text-ink-ghost">{doc.view_count} views</span>
      </header>

      {/* Title */}
      <div className="px-6 py-4 border-b border-border-dim">
        <h1 className="text-lg font-semibold text-ink">{doc.title}</h1>
        <p className="text-[11px] text-ink-ghost font-mono mt-1">Shared document</p>
      </div>

      {/* Tabs */}
      <div className="flex items-center h-9 px-6 border-b border-border-dim bg-inset">
        <button
          onClick={() => setTab("prd")}
          className={`h-full px-3 text-[11px] font-mono uppercase tracking-wider cursor-pointer relative ${
            tab === "prd" ? "text-ink" : "text-ink-ghost hover:text-ink-dim"
          }`}
        >
          PRD
          {tab === "prd" && <span className="absolute bottom-0 left-2 right-2 h-[2px] bg-orange rounded-t" />}
        </button>
        <button
          onClick={() => setTab("workflow")}
          className={`h-full px-3 text-[11px] font-mono uppercase tracking-wider cursor-pointer relative ${
            tab === "workflow" ? "text-ink" : "text-ink-ghost hover:text-ink-dim"
          }`}
        >
          Workflow
          {tab === "workflow" && <span className="absolute bottom-0 left-2 right-2 h-[2px] bg-orange rounded-t" />}
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 max-w-3xl mx-auto w-full">
        <MarkdownRenderer content={content || ""} />
      </div>

      {/* Footer */}
      <footer className="px-6 py-3 border-t border-border text-center">
        <p className="text-[10px] font-mono text-ink-ghost">
          Generated by <a href="/" className="text-aqua hover:underline">FlowPRD</a>
        </p>
      </footer>
    </div>
  );
}
